# -*- coding: utf-8 -*-
"""Week4_Feature_Engineering_Transformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BqDjS2KfhaTx8ExwU_caR6ZzKwVWBl2h
"""

!pip install category_encoders feature-engine

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import (
    StandardScaler,
    MinMaxScaler,
    RobustScaler,
    PowerTransformer,
    OrdinalEncoder
)

import category_encoders as ce

from feature_engine.creation import MathFeatures

print("Libraries Imported Successfully")

df = pd.read_csv('/content/sales_data.csv')

df.head()

df.info()

df.describe()

df.shape

df.columns

df.isnull().sum()

df.fillna(df.median(numeric_only=True), inplace=True)

"""### Feature Engineering: Calculate 'Sales' Column

To resolve the `KeyError: 'Sales'`, I will create a new 'Sales' column by multiplying `unit_price` by `quantity` and then applying the `discount_pct`. This new column will serve as the target variable for subsequent encoding steps.
"""

# Calculate the 'Sales' column
df['Sales'] = df['unit_price'] * df['quantity'] * (1 - df['discount_pct'])

# Display the first few rows with the new 'Sales' column
display(df.head())

categorical_columns = df.select_dtypes(include=['object']).columns

numerical_columns = df.select_dtypes(include=np.number).columns

print("Categorical Columns:")
print(categorical_columns)

print()

print("Numerical Columns:")
print(numerical_columns)

df_ohe = pd.get_dummies(df, columns=categorical_columns, drop_first=True)

df_ohe.head()

encoder = OrdinalEncoder()

for col in categorical_columns:
    df[col] = encoder.fit_transform(df[[col]])

df.head()

from category_encoders import TargetEncoder

target = "Sales"

encoder = TargetEncoder()

# Defensive check: ensure 'Sales' column exists. Re-calculate if missing.
if 'Sales' not in df.columns:
    df['Sales'] = df['unit_price'] * df['quantity'] * (1 - df['discount_pct'])
    print("Warning: 'Sales' column was missing and has been re-calculated.")

for col in categorical_columns:
    df[col] = encoder.fit_transform(df[col], df[target])

scaler = StandardScaler()

df_standard = df.copy()

df_standard[numerical_columns] = scaler.fit_transform(df[numerical_columns])

df_standard.head()

minmax = MinMaxScaler()

df_minmax = df.copy()

df_minmax[numerical_columns] = minmax.fit_transform(df[numerical_columns])

df_minmax.head()

robust = RobustScaler()

df_robust = df.copy()

df_robust[numerical_columns] = robust.fit_transform(df[numerical_columns])

df_robust.head()

df_log = df.copy()

for col in numerical_columns:
    if (df_log[col] >= 0).all():
        df_log[col] = np.log1p(df_log[col])

df_log.head()

power = PowerTransformer(method='box-cox')

positive_cols = []

for col in numerical_columns:
    if (df[col] > 0).all():
        positive_cols.append(col)

df_boxcox = df.copy()

df_boxcox[positive_cols] = power.fit_transform(df_boxcox[positive_cols])

df_boxcox.head()

df["Feature_Interaction"] = df[numerical_columns[0]] * df[numerical_columns[1]]

df.head()

df["order_date"] = pd.to_datetime(df["order_date"])

df["Year"] = df["order_date"].dt.year

df["Month"] = df["order_date"].dt.month

df["Day"] = df["order_date"].dt.day

df["Weekday"] = df["order_date"].dt.day_name()

df.head()

df["Total_Value"] = df[numerical_columns[0]] + df[numerical_columns[1]]

df.head()

plt.figure(figsize=(8,5))

sns.histplot(df[numerical_columns[0]], kde=True)

plt.title("Original Distribution")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df_log[numerical_columns[0]], kde=True)

plt.title("Log Transformed Distribution")

plt.show()

plt.figure(figsize=(12,8))

sns.heatmap(df.corr(numeric_only=True),
            annot=True,
            cmap="coolwarm")

plt.show()

df.to_csv("feature_engineered_sales_data.csv", index=False)

print("Dataset Saved Successfully")

from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("standard_scaler", StandardScaler())
])

print(pipeline)

